# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 01:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 8, 1, 32, 30, 133178, tzinfo=utc)),
        ),
    ]
